# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     3

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Uncle's Blog
description: 技术与人文
keywords: Write
url: https://unclethree.github.io
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 3en
    email: daodangege+aboutme@gmail.com
    imageLink: /images/header.jpg
    simpleIntro: 为学日益，为道日损，损之又损，以至于无为
    detailIntro:
      <img src="http://omupinpjt.bkt.clouddn.com/bird.jpg">
      <p></p>
      <p></p>
      <p></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-facebook
    url: http://facebook.com/
  - class: icon-github-alt
    url: https://github.com/UncleThree/
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: https://plus.google.com/116595571760191938657/about

#Links
customLinks:
  - item:
    - text: windows php list
      url: http://windows.php.net/downloads/releases/archives/
    - text: php内核
      url: http://www.yiifans.com/portal.php?mod=view&aid=474/
    message: PHP    
  - item:
    - text: GitHub 中国区
      url: http://creatist.cn/rank/ 
    message: GitHub


#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-58146229-1

#baidu tongji
baiduTongji:
  config: false
  id: c12b560f0372d5995701449b9eac606c

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: false
  id: 9leg

#baidu share config
baiduShare:
  config: false